var annotated =
[
    [ "_attribute_info", "struct__attribute__info.html", "struct__attribute__info" ],
    [ "_classes", "struct__classes.html", "struct__classes" ],
    [ "_code_attribute", "struct__code__attribute.html", "struct__code__attribute" ],
    [ "_constant_info", "struct__constant__info.html", "struct__constant__info" ],
    [ "_exception_table", "struct__exception__table.html", "struct__exception__table" ],
    [ "_field_info", "struct__field__info.html", "struct__field__info" ],
    [ "_line_number_table", "struct__line__number__table.html", "struct__line__number__table" ],
    [ "_local_variable_table", "struct__local__variable__table.html", "struct__local__variable__table" ],
    [ "_method_info", "struct__method__info.html", "struct__method__info" ],
    [ "ATTRIBUTE_POOL", "struct_a_t_t_r_i_b_u_t_e___p_o_o_l.html", "struct_a_t_t_r_i_b_u_t_e___p_o_o_l" ],
    [ "CLASS", "struct_c_l_a_s_s.html", "struct_c_l_a_s_s" ],
    [ "CLASS_LOADER", "struct_c_l_a_s_s___l_o_a_d_e_r.html", "struct_c_l_a_s_s___l_o_a_d_e_r" ],
    [ "CONSTANT_POOL", "struct_c_o_n_s_t_a_n_t___p_o_o_l.html", "struct_c_o_n_s_t_a_n_t___p_o_o_l" ],
    [ "DADOS", "struct_d_a_d_o_s.html", "struct_d_a_d_o_s" ],
    [ "ERRORS", "struct_e_r_r_o_r_s.html", "struct_e_r_r_o_r_s" ],
    [ "FIELD_POOL", "struct_f_i_e_l_d___p_o_o_l.html", "struct_f_i_e_l_d___p_o_o_l" ],
    [ "FRAME", "struct_f_r_a_m_e.html", "struct_f_r_a_m_e" ],
    [ "HEAP", "struct_h_e_a_p.html", "struct_h_e_a_p" ],
    [ "JVM", "struct_j_v_m.html", "struct_j_v_m" ],
    [ "JVM_INSTRUCTION", "struct_j_v_m___i_n_s_t_r_u_c_t_i_o_n.html", "struct_j_v_m___i_n_s_t_r_u_c_t_i_o_n" ],
    [ "METHOD_AREA", "struct_m_e_t_h_o_d___a_r_e_a.html", "struct_m_e_t_h_o_d___a_r_e_a" ],
    [ "METHOD_POOL", "struct_m_e_t_h_o_d___p_o_o_l.html", "struct_m_e_t_h_o_d___p_o_o_l" ],
    [ "STACK", "struct_s_t_a_c_k.html", "struct_s_t_a_c_k" ],
    [ "UTIL", "struct_u_t_i_l.html", "struct_u_t_i_l" ]
];